<a href="https://colab.research.google.com/github/avellar1975/puc_minas/blob/main/notebooks/Matematica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src='https://raw.githubusercontent.com/avellar1975/puc_minas/main/img/logo.png'>

# 📐 Matemática para Data Science 
> Para se aprofundar

Com o avanço da tecnologia, a quantidade de dados disponível é cada vez maior. Tal crescimento torna diversas áreas da computação desafiadoras, com a necessidade de desenvolver técnicas eficientes de armazenamento, otimizar algoritmos de machine learning para treiná-los em tempo hábil, trabalhar com computação de alta performance, entre outros desafios. Quando se chega a este nível de complexidade, entender o que está por trás dos panos passa a ser fundamental e muitos conceitos envolvidos vão além da matemática básica. Cálculo, Geometria Analítica e Álgebra Linear, são disciplinas que podem elevar seu nível de compreensão e atuação no universo da computação!

In [7]:
# Importando a biblioteca numpy
import numpy as np

## Cálculo

### Cálculo Diferencial, Descida de Gradiente, Cálculo Integral

https://pt.khanacademy.org/math/differential-calculus

https://pt.khanacademy.org/math/integral-calculus

https://phkonzen.github.io/notas/

## Geometria Analítica

https://pt.khanacademy.org/math/geometry-home/analytic-geometry-topic

https://leandrocruvinel.medium.com/geometria-anal%C3%ADtica-com-python-parte-1-90554f3e862c

https://leandrocruvinel.medium.com/geometria-anal%C3%ADtica-com-python-parte-2-6ca9d7173f8

https://leandrocruvinel.medium.com/geometria-anal%C3%ADtica-parte-3-a922d808e5a2

In [6]:
# Fórmula da distância entre dois pontos


def distancia(xa, ya, xb, yb):
    dx = xa - xb
    dy = ya - yb
    dist = (dx ** 2 + dy ** 2) ** 0.5
    return dist

distancia(-6, -4, 1, 7)

13.038404810405298

## Álgebra Linear

https://pt.khanacademy.org/math/linear-algebra

https://algebralinearufcg.github.io/templates/program-list.html

### Vetores e Matrizes

Vetor é o principal objeto de estudo de um curso de geometria analítica. Por isso, que além de estudar os conceitos envolvidos e as interpretações geométricas, as operações entre vetores são estudadas. As quatro operações mais comuns são: soma, multiplicação por escalar, produto escalar e produto misto. É possível fazer as quatro operações utilizando a biblioteca numpy.

In [10]:
vetor_u = np.array([1, -2, 0])
vetor_v = np.array([0, 2, 2])

In [11]:
# soma do vetor u com o vetor v
resultado = vetor_u + vetor_v
print(resultado)

[1 0 2]


In [12]:
# multiplicação do vetor u pelo escalar 7
resultado = 7 * vetor_u
print(resultado)

[  7 -14   0]


In [13]:
# produto escalar de u com v
resultado = np.dot(vetor_u, vetor_v)
print(resultado)

-4


In [14]:
# produto vetorial de u com v
resultado = np.cross(vetor_u, vetor_v)
print(resultado)

[-4 -2  2]
